### PR TITLE
Added support for MTV500ER devices (shutters)

### PR DESCRIPTION
**Pull request by nmaupu**

### CODE REVIEW

**Comment by EinarBergsson** [comment]
Can anyone tell me how to control the shutters?  I have managed to get it to connect to the YOKIS device on the shutter and I can toggle the shutter up and down, however, there is no command that I can see to make it only go down or make it only go up.  Also, I have notice that the software stays in ON_OFF mode and does not go to SHUTTER mode.  Any assistance on this would be very much appreciated.

**Comment by nmaupu** [comment]
Hi, MVR500ER are still a work in progress...
Did you build from this branch or from master ?

According to https://github.com/nmaupu/yokis-hack/pull/7/files#diff-f3ee003b1ce4b176ec762997c953c5e3R192
AFAIK your device should return `0x1e` or `0xef` when pairing. The problem is I don't have those device to test. Someone gave me those info but I cannot confirm it's correct and complete :/

**Comment by nmaupu** [comment]
I made some new changes to better support shutters. You have to build from this branch though...

- Normally, when pairing should be recognized as MVR500 if their return code begins by `0x1e` or `0x2f`. If this is not the case, you will have to check the codes and give it back to me so I can add them here.
- When paired, use `on` command to make shutter go up, `off` command to make shutter go down.
- Use `pause` command to stop shutter from going up or down.

I can also map two new commands for going up or down but it should be basically the same as `on` and `off` commands.

Let me know how that behave on your side.

**Comment by EinarBergsson** [comment]
OK, so I have made sure that I have the right code (by basically installing the code you suggested) and tried it but the behavior is just about the same. Except the toggle is not consistent anymore. Sometimes I need to do it twice.  But here is the output from the pairing process.  The device still seems to be in ON_OFF mode and not SHUTTER as expected. Below is the debug output from the pairing process. Can you see what is happening here?

Regards,
E.

15:43:57.547 -> connected with SmartHome, channel 6
15:43:57.547 -> dhcp client start...
15:43:57.720 -> ip:192.168.1.95,mask:255.255.255.0,gw:192.168.1.1
15:44:02.485 -> Connecting to MQTT 192.168.1.253:1883 ...
15:44:02.519 -> connected
15:44:02.519 -> Publishing homeassistant discovery data... OK
15:44:06.477 -> debug
15:44:06.477 -> Config: DEBUG=1 RAW=0 POLLING=1
15:44:06.477 -> 
15:44:06.477 -> > pm open,type:2 0
15:44:11.374 -> pair
15:44:11.374 -> Hack started, click on the connect button when ready
15:44:11.408 -> STATUS		 = 0x0e RX_DR=0 TX_DS=0 MAX_RT=0 RX_P_NO=7 TX_FULL=0
15:44:11.408 -> RX_ADDR_P0-1	 = 0xbebebebebe 0xc2c2c2c2c2
15:44:11.408 -> RX_ADDR_P2-5	 = 0xc3 0xc4 0xc5 0xc6
15:44:11.408 -> TX_ADDR		 = 0x3f3f733f73
15:44:11.408 -> RX_PW_P0-6	 = 0x03 0x00 0x00 0x00 0x00 0x00
15:44:11.408 -> EN_AA		 = 0x3f
15:44:11.408 -> EN_RXADDR	 = 0x01
15:44:11.408 -> RF_CH		 = 0x02
15:44:11.408 -> RF_SETUP	 = 0x03
15:44:11.408 -> CONFIG		 = 0x0f
15:44:11.408 -> DYNPD/FEATURE	 = 0x00 0x00
15:44:11.441 -> Data Rate	 = 1MBPS
15:44:11.441 -> Model		 = nRF24L01+
15:44:11.441 -> CRC Length	 = 16 bits
15:44:11.441 -> PA Power	 = PA_LOW
15:44:11.441 -> Waiting... timeout=30000
15:44:20.977 -> Buffer data: 49 FF 6 
15:44:20.977 -> Buffer data: 73 3F 37 D5 6 
15:44:20.977 -> Here are the info got from the device:
15:44:20.977 ->   Address: 73 3f 73 3f 3f
15:44:20.977 ->   Channel: 37
15:44:20.977 -> STATUS		 = 0x0e RX_DR=0 TX_DS=0 MAX_RT=0 RX_P_NO=7 TX_FULL=0
15:44:20.977 -> RX_ADDR_P0-1	 = 0x3f3f733f73 0xc2c2c2c2c2
15:44:21.011 -> RX_ADDR_P2-5	 = 0xc3 0xc4 0xc5 0xc6
15:44:21.011 -> TX_ADDR		 = 0x3f3f733f73
15:44:21.011 -> RX_PW_P0-6	 = 0x02 0x00 0x00 0x00 0x00 0x00
15:44:21.011 -> EN_AA		 = 0x00
15:44:21.011 -> EN_RXADDR	 = 0x01
15:44:21.011 -> RF_CH		 = 0x37
15:44:21.011 -> RF_SETUP	 = 0x23
15:44:21.011 -> CONFIG		 = 0x0e
15:44:21.011 -> DYNPD/FEATURE	 = 0x00 0x00
15:44:21.011 -> Data Rate	 = 250KBPS
15:44:21.011 -> Model		 = nRF24L01+
15:44:21.011 -> CRC Length	 = 16 bits
15:44:21.011 -> PA Power	 = PA_LOW
15:44:21.011 -> Payload: 0 0 0 20 0 0 16 0 0 
15:44:21.011 -> E2bp - TX OK
15:44:21.045 -> E2bp - TX OK
15:44:21.045 -> E2bp - TX OK
15:44:21.045 -> E2bp - TX OK
15:44:21.045 -> E2bp - TX OK
15:44:21.045 -> E2bp - TX OK
15:44:21.045 -> E2bp - TX OK
15:44:21.045 -> E2bp - TX OK
15:44:21.045 -> E2bp - TX OK
15:44:21.045 -> E2bp - TX OK
15:44:21.045 -> E2bp - TX OK
15:44:21.045 -> E2bp - TX OK
15:44:21.045 -> E2bp - TX OK
15:44:21.045 -> E2bp - TX OK
15:44:21.045 -> E2bp - TX OK
15:44:21.045 -> E2bp - RX READY
15:44:21.045 -> Received: 00000000 00000000
15:44:21.045 -> Device Status = OFF
15:44:21.080 -> tempDevice - status=UNDEFINED
15:44:21.080 -> Availability: Online
15:44:21.080 -> mode: ON_OFF
15:44:21.080 -> hw: 73 3F
15:44:21.080 -> channel: 37
15:44:21.080 -> serial/version: D5 6/49 FF 6
15:44:21.080 -> 
15:44:21.080 -> >

**Comment by nmaupu** [comment]
Ok, when calling for status (beginning from `15:44:20.977`), I expect a response begining by `0x1e` or `0x2f`. But somehow, your device returns all zeroes :/

So I don't have a good way of detecting this...
I will add a way to manually select this from command line...

**Comment by nmaupu** [comment]
It's already possible when storing configuration (command `save`) when using esp8266...
As far as I know, this is what you use, right ?
To do so, just use the following command after pairing:
```
save shutter01 SHUTTER 
```

`shutter01` is the name of the device you want to use. What is important is to specify `SHUTTER` when saving.

After that, you can display the device information and verify it's in shutter mode:
```
```

**Comment by EinarBergsson** [comment]
OK New problem as I was testing this. Any Ideas why this happens?

11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO
11:19:00.641 -> Publishing homeassistant discovery data... KO

**Comment by nmaupu** [comment]
You have this before or after saving the conf to SPIFFS (`save` command) ?

Most of the time, driver is unable to publish to MQTT server. Can be a bug somehow but MQTT server might be down or network might be unreachable.
Is the server `192.168.1.253:1883` up ? Also check username and password to access it.

Current code does not support disabling MQTT so it's doing it at each loop

**Comment by EinarBergsson** [comment]
Before.  I had compiled the code without SPIFFS included. So when I went and added 1M of SPIFFS, this became a problem. I temporarily sorted it by commenting out the LOG statements. That allowed me to test the save command. And after a reload it all worked. HOWEVER, I am not able to communicate with the system via MQTT.  So something like: mosquitto_pub -t "shutter01/...." -m "OFF" does not work.

**Comment by nmaupu** [comment]
I added a variable to be able to disable MQTT if need be. To do so, just define MQTT_ENABLED=false when compiling (can also be done editing `platformio.ini` file).

If you can't publish to your MQTT server, there is nothing I can do about it 🤷‍♂️ 
Just disable it for now, shutters are not supported yet anyway.

**Comment by EinarBergsson** [comment]
The problem is not that the ESP is not connecting to the MQTT broker. It is more that it is not able to send anything to it.  Looking at the logs I can see the device connecting but nothing is sent to the broker, nor am I able to send commands through the broker to the ESP. 

I am still working on debugging it, but if you again have some pointers that would be great.

**Comment by nmaupu** [comment]
You actually don't need MQTT to test if shutters are working or not.
First, you can just use the serial console and when everything's ok, we can look at potential problems with MQTT.

**Comment by EinarBergsson** [comment]
Sorry, but it probably wasn't clear in my last post. I can now control the shutters perfectly via the Serial console.  I just need the MQTT working and I should be good.  :D

**Comment by nmaupu** [comment]
Ho ! Nice news indeed :)
What kind of MQTT server is it ?

**Comment by EinarBergsson** [comment]
I am using Mosquitto.

**Comment by nmaupu** [comment]
What configuration are you using ?

**Comment by EinarBergsson** [comment]
Standard. I just installed it and it worked. I am not using any TLS or passwords or anything.  It seems to connect to it, but never sends anything. I can see the connection notice in the logfile.

**Comment by nmaupu** [comment]
When compiling, did you set `MQTT_USERNAME` and `MQTT_PASSWORD` to empty strings ?
Looking at the code, I am not sure it supports connecting to a MQTT server without authentication...

Best bet is to configure a dummy username/password on your server and use that.

**Comment by EinarBergsson** [comment]
Tried it and it made no difference.

**Comment by nmaupu** [comment]
What exactly ? Username and password to empty strings or set up a server with authentication and recompiling with those set ?

Also try to publish/subscribe some dummy values from command line with `mosquitto_pub/sub` commands to see if Mosquitto is working as expected. At that point, it's most likely a configuration problem on your side...

**Comment by EinarBergsson** [comment]
I am beginning to think that I may have broken this when I moved the code to the IDE. I am tracing it now. It is a bit of a pain.. but I will get there. I am sure of it.

**Comment by EinarBergsson** [comment]
As I was using a fresh installation of the PubSub library, the maximum size of an MQTT message was the default 128. It took me a while (with a shitload of interruptions) to figure it out, but I needed to change the max size definition in the library. In the PubSubClient.h file there is a definition that looks like this:

#ifndef MQTT_MAX_PACKET_SIZE
#define MQTT_MAX_PACKET_SIZE 128
#endif

I changed it to:

#ifndef MQTT_MAX_PACKET_SIZE
#define MQTT_MAX_PACKET_SIZE 1024
#endif

...and it all hummed back to life. Now I am going to test the MQTT to see if that is as I want it, and if so... Thank you for the great help and the work you have done on this.

**Comment by nmaupu** [comment]
You should use platform.io command line tools for compiling (see readme), it's already handled in the conf:
https://github.com/nmaupu/yokis-hack/blob/master/platformio.ini#L41
It would avoid you many pains and problems ;)

**Comment by EinarBergsson** [comment]
You are right, but I am using the IDE. Changing the library code was not great, I even tried to add the change before the include, and it didn't work. Don't know why. But I leave that to others more clever to figure out.

Anyway, yes I realized that the MQTT was not handling the shutter, so I changed the callback function to make that work. 
Here it is:

void mqttCallback(char* topic, uint8_t* payload, unsigned int length) {
    char* tok;
    char* mTokBuf = NULL;
    char* mTopic = NULL;
    char* mCmnd = NULL;
    char* mPayload = NULL;
    Device* d;
    size_t len;

    // Topic copy
    len = strlen(topic);
    mTopic = new char[len + 1];
    strncpy(mTopic, topic, len);
    mTopic[len] = 0;

    // Get device
    mTokBuf = new char[len + 1];
    strncpy(mTokBuf, mTopic, len);
    mTokBuf[len] = 0;
    tok = strtok(mTokBuf, "/");  // device name
    d = Device::getFromList(devices, MQTT_MAX_NUM_OF_YOKIS_DEVICES, tok);

    // If we update this device too soon, ignore the payload
    unsigned long now = millis();
    if (d->getLastUpdateMillis() + MQTT_UPDATE_MILLIS_WINDOW > now) {
        LOG.println(
            "Ignoring MQTT message: received too soon for this device");
        LOG.print("Last update: ");
        LOG.println(d->getLastUpdateMillis(), DEC);
        LOG.print("This update: ");
        LOG.println(now, DEC);
        LOG.print("Difference: ");
        LOG.println(now - d->getLastUpdateMillis());

        delete[] mTopic;
        delete[] mTokBuf;
        return;
    }

    // Get cmnd type (POWER or BRIGHTNESS)
    tok = strtok(NULL, "/");  // cmnd
    tok = strtok(NULL, "/");  // POWER or BRIGHTNESS
    len = strlen(tok);
    mCmnd = new char[len + 1];
    strncpy(mCmnd, tok, len);
    mCmnd[len] = 0;

    // Get payload
    mPayload = new char[length + 1];
    strncpy(mPayload, (char*)payload, length);  // consider payload as char*
    mPayload[length] = 0;

    // Processing MQTT message
    IrqManager::irqType = E2BP;
    g_bp->setDevice(d);
    switch (d->getMode()) {
        case ON_OFF:
        case SHUTTER:
        case NO_RCPT:
            if (strcmp(mPayload, "ON") == 0) {
                g_bp->on();
                Serial.println("Setting On....");
            } else if (strcmp(mPayload, "OFF") == 0) {
                g_bp->off();
                Serial.println("Setting Off....");
            } else if (strcmp(mPayload, "PAUSE") == 0) {
                g_bp->pauseShutter();
                Serial.println("Pausing shutter....");
            }
            g_mqtt->notifyPower(d);
            break;
        case DIMMER:
            // brightness will be 0 for anything that is not a number
            // so will set light to OFF for all possible POWER cases (ON OR
            // OFF) HASS will send only POWER OFF, never POWER ON because
            // on_command_type=brightness set on MQTT configuration (see
            // MqttHass class)
            int brightness = (uint8_t)atoi(mPayload);

            switch (brightness) {
                case BRIGHTNESS_OFF:
                    g_bp->off();
                    break;
                case BRIGHTNESS_MIN:
                    g_bp->dimmerMin();
                    break;
                case BRIGHTNESS_MID:
                    g_bp->dimmerMid();
                    break;
                default:  // MAX values
                    g_bp->on();
                    break;
            }

            g_mqtt->notifyBrightness(d);
            break;
    }

    delete[] mTopic;
    delete[] mTokBuf;
    delete[] mCmnd;
    delete[] mPayload;
}

**Comment by EinarBergsson** [comment]
And I am back!  So I have managed to get one shutter (out of ten) to work perfectly. Now that I am trying to pair a second one I am having zero luck. When I type in the pair command and then go and press the connect button on the device which is 3 meters away...nothing...just timeout. Any bright ideas?

**Comment by nmaupu** [comment]
Maybe, try resetting the remote and repair it with the MVR. It's weird though because the pairing address is always the same...

**Comment by EinarBergsson** [comment]
Do I need the remote to do this?

**Comment by nmaupu** [comment]
Yes ofc, I don't know if there is an english version of it but from the manual (page 3, `4)`):
https://www.yokis.fr/wp-content/uploads/2019/12/notice-MVR500.pdf
You need to make 25 pulses on the remote button.
Beware though, it resets all configuration related to this button...

Before doing that, you can try the yokis procedure to make a copy of the button's configuration to another yokis remote/button to see if that works (5 pulses on the target button and long press on the button to copy).

You can also try to power cycle your ESP8266 and NRF24 just in case.

**Comment by EinarBergsson** [comment]
Based on your reply I realized that 25 presses would only reset the module if I did 23 first. But it worked. Thank you.  

And now I am wondering why my range on this is so limited?  I kinda have to be right next to the MVR for it to work, and if I move to the next room there is no way to get it to function and I get continuous off-line notices. What sort of range can I expect out of this?

**Comment by EinarBergsson** [comment]
Hey Nicolas,

I am having a range issue, and only able to connect to 1 or 2 shutters at a
time. I have read that the Yoko's devices can be put on a radio bus, and I
that way effectively meshed together. Is that something that is supported?

Reg.,
E.

**Comment by nmaupu** [comment]
I never tested the radio bus so I don't know how it behaves. Theoretically, it shouldn't make a big difference though...
What do you mean by 1 or 2 at a time? 

For your range problem, what kind of NRF24 have you got? The ones with or without antenna?

**Comment by EinarBergsson** [comment]
So I am saying that the unit cannot communicate with the Yokis devices if
they are not inside a meter and a half away and that I am unable to get
them to work through walls.

The NRF24 is the one with the screw-on antenna. I thought the range on
those would be a lot better.

One thing to note, there is terrible noise here on the 2.4GHz band, so that
may have an effect, however that said, my copious amount of BT and WiFi
devices do not seem to have issues.

Regards,
Einar Bergsson

**Pull request merged**
